Update npm-publish-github-packages.yml

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -23,22 +23,27 @@ jobs:
           sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
             # Ensure PATH includes the location of PM2 and Node.js
             export PATH=$PATH:/root/.nvm/versions/node/v20.16.0/bin
-
+            
+            # Navigate to the application directory
             cd $APP_PATH
 
             # Pull the latest code from the repository
-            git pull 
+            echo "Pulling latest code from repository..."
+            git pull origin main
 
             # Install dependencies
+            echo "Installing dependencies..."
             yarn 
-          
-           # Build 
+
+            # Build the project
+            echo "Building the project..."
             yarn build 
 
-            # Reload PM2 process
-            pm2 reload 1
+            # Reload PM2 process (use the process name if you’re unsure of the ID)
+            echo "Reloading PM2 process..."
+            pm2 reload app-name || { echo 'PM2 reload failed'; exit 1; }
 
-            # Save pm2 
-            pm2 save
-            
+            # Save PM2 process list
+            echo "Saving PM2 process list..."
+            pm2 save || { echo 'PM2 save failed'; exit 1; }
           EOF
